# Generated by Django 4.0.5 on 2022-09-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=200)),
                ('Marca', models.CharField(max_length=50)),
                ('fabricacion', models.IntegerField()),
                ('fichatecnica', models.FileField(upload_to='vehiculos')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
