# Generated by Django 4.0.5 on 2022-09-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculos',
            new_name='Vehiculo',
        ),
    ]
