# Generated by Django 4.0.5 on 2022-10-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0003_alter_vehiculo_created_alter_vehiculo_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='updated',
            new_name='revision',
        ),
    ]
