# Generated by Django 4.0.5 on 2022-10-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0004_rename_updated_vehiculo_revision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='fichatecnica',
            new_name='Adjunto',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='created',
            new_name='Creación',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Modelo',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Marca',
            new_name='Sector',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='fabricacion',
        ),
    ]
