# Generated by Django 4.0.5 on 2022-10-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0005_rename_fichatecnica_vehiculo_adjunto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Creación',
            new_name='Alta',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='revision',
            new_name='Revision',
        ),
    ]
