# Generated by Django 4.0.5 on 2022-10-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0009_vehiculo_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='Estado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
