# Generated by Django 4.0.5 on 2022-11-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0010_vehiculo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='Codigo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
