# Generated by Django 4.0.5 on 2022-11-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0011_vehiculo_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LasauPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sector', models.CharField(max_length=50)),
            ],
        ),
    ]
