# Generated by Django 4.0.5 on 2022-11-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0013_alter_vehiculo_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasauplanta',
            name='Sector',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='Nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
