# Generated by Django 4.0.5 on 2022-11-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaApp', '0014_alter_lasauplanta_sector_alter_vehiculo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='Nombre',
            field=models.CharField(error_messages={'Invalido': 'El registro ya existe!'}, max_length=200, unique=True),
        ),
    ]
