# Generated by Django 4.0.5 on 2022-08-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='procedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('initdate', models.DateField()),
                ('revisiondate', models.DateField()),
                ('status', models.CharField(choices=[('ACT', 'Activo'), ('REV', 'Revisión'), ('OBS', 'Obsoleto')], default='ACT', max_length=40)),
            ],
        ),
    ]
