# Generated by Django 4.0.5 on 2022-08-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lubesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('initdate', models.DateField()),
                ('revisiondate', models.DateField()),
                ('status', models.CharField(choices=[('ACT', 'Activo'), ('REV', 'Revisión'), ('OBS', 'Obsoleto')], default='ACT', max_length=40)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='procedimientos',
        ),
    ]
